export type PlantGroupKey =
    | "bodembedekkers"
    | "vaste-planten"
    | "heesters-struiken"
    | "bomen"
    | "zoek-zelf";

export type ViewMode = "grid" | "list";

export type DummyPlant = {
    id: string;
    group: Exclude<PlantGroupKey, "zoek-zelf">;
    name: string;
    latinName: string;
    badge?: string;
    stockLabel: string;
    imageSrc: string;
};

export const GROUP_OPTIONS: Array<{
    key: PlantGroupKey;
    label: string;
    variant?: "primary" | "secondary" | "search";
}> = [
        { key: "bodembedekkers", label: "Bodembedekkers", variant: "primary" },
        { key: "vaste-planten", label: "Vaste planten", variant: "secondary" },
        { key: "heesters-struiken", label: "Heesters & struiken", variant: "secondary" },
        { key: "bomen", label: "Bomen", variant: "secondary" },
        { key: "zoek-zelf", label: "Zoek zelf een plant", variant: "search" },
    ];

export const GROUP_LABELS: Record<PlantGroupKey, string> = {
    "bodembedekkers": "Bodembedekkers",
    "vaste-planten": "Vaste planten",
    "heesters-struiken": "Heesters & struiken",
    bomen: "Bomen",
    "zoek-zelf": "Zoek zelf een plant",
};

export const DUMMY_PLANTS: DummyPlant[] = [
    {
        id: "plant-1",
        group: "bodembedekkers",
        name: "Vinca minor 'Alba'",
        latinName: "Maagdenpalm",
        badge: "Zeer geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/vinca_minor_alba.jpg",
    },
    {
        id: "plant-2",
        group: "bodembedekkers",
        name: "Pachysandra terminalis 'Green Carpet'",
        latinName: "Schaduwkruid",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/pachysandra_terminalis_green_carpet.jpg",
    },
    {
        id: "plant-3",
        group: "bodembedekkers",
        name: "Geranium macrorrhizum",
        latinName: "Ooievaarsbek",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/geranium_macrorrhizum.jpg",
    },
    {
        id: "plant-4",
        group: "bodembedekkers",
        name: "Ajuga reptans",
        latinName: "Kruipend zenegroen",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/ajuga_reptans.jpg",
    },
    {
        id: "plant-5",
        group: "bodembedekkers",
        name: "Waldsteinia ternata",
        latinName: "Goudaardbei",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/waldsteinia_ternata.jpg",
    },
    {
        id: "plant-6",
        group: "bodembedekkers",
        name: "Cotoneaster dammeri",
        latinName: "Dwergmispel",
        badge: "Goede aanvulling",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/cotoneaster_dammeri.jpg",
    },
    {
        id: "plant-7",
        group: "bodembedekkers",
        name: "Epimedium perralchicum",
        latinName: "Elfenbloem",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/epimedium_perralchicum.jpg",
    },
    {
        id: "plant-8",
        group: "bodembedekkers",
        name: "Lysimachia nummularia",
        latinName: "Penningkruid",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/lysimachia_nummularia.jpg",
    },
    {
        id: "plant-9",
        group: "bodembedekkers",
        name: "Thymus serpyllum",
        latinName: "Kruiptijm",
        badge: "Zeer geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/thymus_serpyllum.jpg",
    },
    {
        id: "plant-10",
        group: "bodembedekkers",
        name: "Sedum spurium",
        latinName: "Vetkruid",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/sedum_spurium.jpg",
    },
    {
        id: "plant-11",
        group: "bodembedekkers",
        name: "Lamium maculatum",
        latinName: "Gevlekte dovenetel",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/lamium_maculatum.jpg",
    },
    {
        id: "plant-12",
        group: "bodembedekkers",
        name: "Alchemilla mollis",
        latinName: "Vrouwenmantel",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/alchemilla_mollis.jpg",
    },
    {
        id: "plant-13",
        group: "vaste-planten",
        name: "Salvia nemorosa",
        latinName: "Bossalie",
        badge: "Zeer geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/salvia_nemorosa.jpg",
    },
    {
        id: "plant-14",
        group: "vaste-planten",
        name: "Echinacea purpurea",
        latinName: "Zonnehoed",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/echinacea_purpurea.jpg",
    },
    {
        id: "plant-15",
        group: "vaste-planten",
        name: "Lavandula angustifolia",
        latinName: "Lavendel",
        badge: "Zeer geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/lavandula_angustifolia.jpg",
    },
    {
        id: "plant-16",
        group: "vaste-planten",
        name: "Rudbeckia fulgida",
        latinName: "Zonnehoed (gele)",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/rudbeckia_fulgida.jpg",
    },
    {
        id: "plant-17",
        group: "vaste-planten",
        name: "Geranium sanguineum",
        latinName: "Bloedooievaarsbek",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/geranium_sanguineum.jpg",
    },
    {
        id: "plant-18",
        group: "vaste-planten",
        name: "Nepeta faassenii",
        latinName: "Kattenkruid",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/nepeta_faassenii.jpg",
    },
    {
        id: "plant-19",
        group: "vaste-planten",
        name: "Helleborus orientalis",
        latinName: "Kerstroos",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/helleborus_orientalis.jpg",
    },
    {
        id: "plant-20",
        group: "vaste-planten",
        name: "Heuchera micrantha",
        latinName: "Purperklokje",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/heuchera_micrantha.jpg",
    },
    {
        id: "plant-21",
        group: "vaste-planten",
        name: "Phlox paniculata",
        latinName: "Vlambloem",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/phlox_paniculata.jpg",
    },
    {
        id: "plant-22",
        group: "vaste-planten",
        name: "Astilbe chinensis",
        latinName: "Pluimspirea",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/astilbe_chinensis.jpg",
    },
    {
        id: "plant-23",
        group: "vaste-planten",
        name: "Campanula poscharskyana",
        latinName: "Klokjesbloem",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/campanula_poscharskyana.jpg",
    },
    {
        id: "plant-24",
        group: "vaste-planten",
        name: "Achillea millefolium",
        latinName: "Duizendblad",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/achillea_millefolium.jpg",
    },
    {
        id: "plant-25",
        group: "heesters-struiken",
        name: "Hydrangea macrophylla",
        latinName: "Hortensia",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/hydrangea_macrophylla.jpg",
    },
    {
        id: "plant-26",
        group: "heesters-struiken",
        name: "Cornus alba",
        latinName: "Rode kornoelje",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/cornus_alba.jpg",
    },
    {
        id: "plant-27",
        group: "bomen",
        name: "Acer campestre",
        latinName: "Veldesdoorn",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/acer_campestre.jpg",
    },
    {
        id: "plant-28",
        group: "bomen",
        name: "Amelanchier lamarckii",
        latinName: "Krentenboompje",
        badge: "Zeer geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/amelanchier_lamarckii.jpg",
    },
    {
        id: "plant-29",
        group: "bomen",
        name: "Carpinus betulus",
        latinName: "Haagbeuk",
        badge: "Geschikt",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/carpinus_betulus.jpg",
    },
    {
        id: "plant-30",
        group: "bomen",
        name: "Betula pendula",
        latinName: "Ruwe berk",
        badge: "Goede aanvulling",
        stockLabel: "Op voorraad",
        imageSrc: "/images/plantenfotos/betula_pendula.jpg",
    },
    {
        id: "plant-31",
        group: "bomen",
        name: "Prunus avium",
        latinName: "Zoete kers",
        badge: "Geschikt",
        stockLabel: "Binnen een week leverbaar",
        imageSrc: "/images/plantenfotos/prunus_avium.jpg",
    },
];